### ISSUE TITLE
do you think this implementation of a soft body could work on a rigidbody2d?

### ISSUE THREAD

**Issue by unforgivenvirtuoso** [Lynext/GodotSoftBody2D#1]
a rigid body is essential for the game im trying to create. Thank you and sorry if this is the wrong place to ask.

**Comment by Lynext** [comment]
@unforgivenvirtuoso Yes, it will definitely work with a 2d rigidbody. I have some work on this but it will be some time before I upload it to GitHub. In the script there are "points" in the "blob" array. You have to create seperate RigidBody2D's for each one of them. Then you can move them around and you have a soft body that can interact with environment :)

**Comment by unforgivenvirtuoso** [comment]
Oh wow thank you so much for using a FOS license youre a life saver have a great day

**Comment by Lynext** [comment]
@unforgivenvirtuoso No problem, have a nice day too :)
